Use runno-clang for C/C++
taybenlor/runno pull request #195
Opened 2022-04-07 13:09 UTC by LukePrior

I think this solves #193

2022-04-07 13:14 UTC, taybenlor commented on packages/runtime/src/provider.ts
> -        `clang -cc1 -Werror -triple wasm32-unkown-wasi -isysroot /sys -internal-isystem /sys/include -ferror-limit 4 -fmessage-length 80 -fcolor-diagnostics -O2 -emit-obj -o ./program.o ${entryPath}`
Instead of removing the `clang` runtime I'd like to see `clang` here switched for `runno-clang`.

2022-04-07 13:18 UTC, taybenlor commented
I'd be happy to try and help you get the dev environment running locally! It's probably got some quirks because I've been devving it by myself.

How did you go following the instructions in the `README.md`?

2022-04-09 03:51 UTC, taybenlor requested changes
Similar issue to before, now you're using the C++ args for the C version.

2022-04-09 03:54 UTC, LukePrior commented on packages/runtime/src/provider.ts
> +        `runno-wasm-ld --no-threads --export-dynamic -z stack-size=1048576 -L/sys/lib/wasm32-wasi /sys/lib/wasm32-wasi/crt1.o program.o -lc -lc++ -lc++abi -o ./program.wasm`,
Sorry, that makes perfect sense, I _think_ now it's right.

2022-04-09 04:03 UTC, taybenlor commented
Awesome, this looks right. I'm just going to test it works locally.

2022-04-09 04:21 UTC, taybenlor requested changes
Alright, annoyingly this doesn't seem to work. Here's the output I get locally for your example:

```
In file included from program:1:
In file included from /sys/include/stdlib.h:6:
In file included from /sys/include/__functions_malloc.h:7:
/sys/include/stddef.h:30:15: fatal error: 'stddef.h' file not found
#include_next <stddef.h>
              ^~~~~~~~~~
1 error generated.
```

My clang knowledge is pretty limited and this setup is a bit odd. I think you'll have to get it running locally on your machine to start debugging it.

Could you go through the instructions in the `README.md` under `## Running locally` to get it going?

Currently you'll need to run `npm run dev` separately inside each of the `client` and `website` directories. When you modify the `runtime` you'll need to run build again.

If you have any issues with that comment here and I'll help you out.

I'll work on improving the local dev experience as well.

2022-04-09 04:23 UTC, taybenlor commented
If you'd like to organise a pairing session so we can work through it together I'd also be happy to do that. Just email `runno@taybenlor.com` and we can coordinate a video call during the week (12th or 13th will be best for me).

2022-04-09 13:12 UTC, LukePrior commented
I will have a look into this further when I have some time, not sure when so I will close this for now.

2022-04-09 13:12 UTC, closed without merging